name: Invoke Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  invoke:
    uses: ./.github/workflows/demo-9-reusable-workflow.yml
    with:
      build-command: "python setup.py build"